name: Update Progress Graph
on: [push] # Runs every time you push code
permissions:
      contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python update_graph.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add progress_graph.png
          git commit -m "Auto-update progress graph" || exit 0
          git push
